recipe/urls.py
from django.urls import path
from . import views

app_name = 'recipe'

urlpatterns = [
    path('', views.view_recipes, name='view_recipes'),
    path('view_user_recipes/', views.view_user_recipes, name='view_user_recipes'),
    path('view_recipe_detail/<int:id_of_recipe>/', views.view_recipe_detail, name='view_recipe_detail'),
    path('create/', views.create_recipe, name='create_recipe'),
    path('update/<int:id>/', views.update_recipe, name='update_recipe'),
    path('delete/<int:id>/', views.delete_recipe, name='delete_recipe'),
    path('<int:id_of_recipe>/create_ingrediants/', views.create_ingrediants, name='create_ingrediants'),
    path('<int:id_of_recipe>/update_ingrediants/<int:id>/', views.update_ingrediants, name='update_ingrediants'),
    path('<int:id_of_recipe>/delete_ingrediants/<int:id>/', views.delete_ingrediants, name='delete_ingrediants'),
    path('<int:id_of_recipe>/create_instruction/', views.create_instructions, name='create_instruction'),
    path('<int:id_of_recipe>/update_instruction/<int:id>/', views.update_instructions, name='update_instruction'),
    path('<int:id_of_recipe>/delete_instructions/<int:id>/', views.delete_instructions, name='delete_instructions'),
]

rps/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('profile/', include('user.urls')),
    path('recipe/', include('recipe.urls',namespace='recipe')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

recipe/models.py
from django.db import models
from django.contrib.auth.models import User

class CategoryModel(models.Model):

    CATEGORIES = (
        ('appetizers and snack', 'APPETIZERS AND SNACK'),
        ('main dishes', 'MAIN DISHES'),
        ('bread and blaked goods', 'BREAD AND BLAKED GOODS'),
        ('desserts', 'DESSERTS'),
        ('salads and slides', 'SALADS AND SLIDES'),
        ('soups and stews', 'SOUPS AND STEWS'),
        ('not specified', 'NOT SPECIFIED'),
    )
    name = models.CharField(max_length=255, choices= CATEGORIES)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    
class RecipeModel(models.Model):
    category = models.ForeignKey(CategoryModel, on_delete=models.CASCADE, related_name="category")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_by')
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='recipe_images/', default='recipe.svg', blank=True, null=True)
    description = models.TextField()

    def __str__(self):
        return self.name
    
class InstructionModel(models.Model):
    recipe = models.ForeignKey(RecipeModel, on_delete=models.CASCADE, related_name='instructions')
    step_number = models.PositiveIntegerField()
    instruction_text = models.TextField(null=True)

    class Meta:
        ordering = ['step_number']

class IngrediantsModel(models.Model):
    recipe = models.ForeignKey(RecipeModel, on_delete=models.CASCADE, related_name='ingrediants')
    name = models.CharField(max_length=100)

recipe/forms.py
from django import forms
from .models import RecipeModel, InstructionModel, IngrediantsModel

SELECT_AREA = 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'

INPUT_AREA = 'rounded-none rounded-e-lg bg-gray-50 border text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'

FOR_IMAGE = 'block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400'

TEXT_AREA = 'block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'

class RecipeForm(forms.ModelForm):
    class Meta:
        model = RecipeModel
        fields = ['category', 'name', 'image', 'description']
        widgets = {
            'category': forms.Select(attrs={'class': SELECT_AREA}),
            'name': forms.TextInput(attrs={'class': INPUT_AREA, 'placeholder': 'Recipe Name'}),
            'image': forms.FileInput(attrs={'class': FOR_IMAGE}),
            'description': forms.Textarea(attrs={'class': TEXT_AREA, 'placeholder': 'Enter description here', 'rows': 3}),
        }

class InstructionForm(forms.ModelForm):
    class Meta:
        model = InstructionModel
        fields = ['step_number', 'instruction_text']
        widgets = {
            'step_number': forms.NumberInput(attrs={'class': INPUT_AREA}),
            'instruction_text': forms.Textarea(attrs={'class': TEXT_AREA, 'placeholder': 'Enter instruction'}),
        }

class IngrediantsForm(forms.ModelForm):
    class Meta:
        model = IngrediantsModel
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': INPUT_AREA, 'placeholder': 'Ingredient name'}),
        }

recipe/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from .models import RecipeModel, InstructionModel, IngrediantsModel, CategoryModel
from .forms import RecipeForm, InstructionForm, IngrediantsForm

@login_required
def view_user_recipes(request):
    recipes = RecipeModel.objects.filter(created_by = request.user)
    return render(request, 'recipe/view_user_recipes.html', {'recipes': recipes})

@login_required
def view_recipes(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = CategoryModel.objects.all()
    recipes = RecipeModel.objects.all()

    if category_id:
        recipes = recipes.filter(category_id= category_id)

    if query:
        recipes = recipes.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'recipe/view_recipes.html', {'recipes': recipes, 'categories': categories,})

@login_required
def view_recipe_detail(request, id_of_recipe):
    recipe = get_object_or_404(RecipeModel, pk = id_of_recipe)
    ingrediants = IngrediantsModel.objects.filter(recipe_id = id_of_recipe)
    instructions = InstructionModel.objects.filter(recipe_id = id_of_recipe)
    return render(request, 'recipe/view_recipe_detail.html', {'recipe': recipe, 'ing': ingrediants, 'ins': instructions})

@login_required
def create_recipe(request): 

    if (request.method == 'POST'): 
        form = RecipeForm(request.POST, request.FILES)

        if(form.is_valid()):
            recipe = form.save(commit=False)
            recipe.created_by = request.user
            recipe.save()
            messages.success(request, 'Recipe created successfully..')
        
        else:
            messages.error(request, 'Failed to create recipe')
    
    else: 
        form = RecipeForm()
        

    return render(request, 'recipe/forms.html', {'form': form})

@login_required
def update_recipe(request, id):
    recipe = get_object_or_404(RecipeModel, pk = id, created_by = request.user)

    if (request.method == 'POST'): 
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        
        if(form.is_valid()):
            form.save()
            messages.success(request, 'Recipe updated successfully..')

        else:
            messages.error(request, 'Failed to update the recipe')

    else:
        form = RecipeForm(instance=recipe)

    return render(request, 'recipe/forms.html', {'form': form})

@login_required
def delete_recipe(request, id):
    recipe = get_object_or_404(RecipeModel, pk = id, created_by = request.user)
    recipe.delete()
    messages.success(request, 'The recipe is deleted successfully...!!')
    return redirect('home')

@login_required
def create_ingrediants(request, id_of_recipe): 

    if (request.method == 'POST'):
        form = IngrediantsForm(request.POST)
        
        if (form.is_valid()):
            ingrediant = form.save(commit=False)
            ingrediant.recipe_id = id_of_recipe
            ingrediant.save()
            messages.success(request, 'Ingrediants created succesflly...')

        else:
            messages.error(request, 'Failed to make the ingrediants...')

    else:
        form = IngrediantsForm()

    return render(request, 'recipe/forms.html', {'form': form})

@login_required
def update_ingrediants(request, id, id_of_recipe):
    recipe = get_object_or_404( RecipeModel, pk = id_of_recipe, created_by = request.user)
    ingrediants = get_object_or_404(IngrediantsModel, pk = id, recipe = recipe)
    if (request.method == 'POST'): 
        form = IngrediantsForm(request.POST, instance= ingrediants)
        if (form.is_valid()):
            form.save()
            messages.success(request, 'Ingrediants updated succesfully...')

        else:
            messages.error(request, 'Failed to update ingrediants')
    else:
        form = IngrediantsForm(instance=ingrediants)

    return render(request, 'recipe/forms.html', {'form': form})

from django.shortcuts import redirect

@login_required
def delete_ingrediants(request, id, id_of_recipe):
    recipe = get_object_or_404(RecipeModel, pk=id_of_recipe, created_by=request.user)
    ingrediant = get_object_or_404(IngrediantsModel, pk=id, recipe=recipe)
    ingrediant.delete()
    messages.success(request, 'Ingrediant deleted successfully..')
    return redirect('recipe:view_recipe_detail', id_of_recipe=id_of_recipe)

@login_required
def create_instructions(request, id_of_recipe):
    recipe = get_object_or_404(RecipeModel, pk=id_of_recipe, created_by=request.user)
    
    if request.method == 'POST':
        form = InstructionForm(request.POST)
        if form.is_valid():
            instruction = form.save(commit=False)
            instruction.recipe = recipe
            instruction.save()
            messages.success(request, 'Instructions created successfully...')
            return redirect('recipe:create_instruction', id_of_recipe=recipe.pk) 
        else:
            messages.error(request, 'Failed to create instructions...')
    else:
        form = InstructionForm()

    return render(request, 'recipe/forms.html', {'form': form})

@login_required
def update_instructions(request, id, id_of_recipe):

    recipe = get_object_or_404(RecipeModel, pk=id_of_recipe, created_by=request.user)
    instruction = get_object_or_404(InstructionModel, pk=id, recipe=recipe)

    if request.method == 'POST':
        form = InstructionForm(request.POST, instance=instruction)
        if form.is_valid():
            form.save()
            messages.success(request, 'Instruction updated successfully.')
        else:
            messages.error(request, 'Failed to update instruction.')
    else:
        form = InstructionForm(instance=instruction)

    return render(request, 'recipe/forms.html', {'form': form})


@login_required
def delete_instructions(request, id, id_of_recipe):
    recipe = get_object_or_404(RecipeModel, pk=id_of_recipe, created_by=request.user)
    instruction = get_object_or_404(InstructionModel, pk=id, recipe=recipe)

    instruction.delete()
    messages.success(request, 'Instruction deleted successfully.')
    return redirect('recipe:view_recipe_detail', id_of_recipe=id_of_recipe)

recipe/templates/recipe/view_recipe_detail.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}
<div class='max-w-screen-xl mx-auto p-6 md:px-10 md:py-10 rounded-md'>
    <h1 class='mb-10 text-2xl font-bold text-center text-white'>Recipe Detail</h1>

    <div class='grid md:grid-cols-2 gap-6'>
        <!-- Left side: image -->
        <div class='md:col-span-1'>
            <img src="{{ recipe.image.url }}" alt="recipe image" class="rounded w-full object-cover max-h-96">
        </div>

        <!-- Right side: tabs -->
        <div class='md:col-span-1'>
            <div class="mb-4 border-b border-gray-200 dark:border-gray-700">
                <ul class="flex flex-wrap -mb-px text-sm font-medium text-center" id="tab-list" role="tablist">
                    <li class="me-2" role="presentation">
                        <button class="tab-btn inline-block p-4 border-b-2 rounded-t-lg border-blue-600 text-blue-600" 
                                id="Details-tab" type="button"
                                data-tab="Details"
                                aria-selected="true">
                            Details
                        </button>
                    </li>
                    <li class="me-2" role="presentation">
                        <button class="tab-btn inline-block p-4 border-b-2 rounded-t-lg hover:text-gray-300 hover:border-gray-300" 
                                id="description-tab" type="button"
                                data-tab="description"
                                aria-selected="false">
                            Description
                        </button>
                    </li>
                    <li class="me-2" role="presentation">
                        <button class="tab-btn inline-block p-4 border-b-2 rounded-t-lg hover:text-gray-300 hover:border-gray-300" 
                                id="ingrediants-tab" type="button"
                                data-tab="ingrediants"
                                aria-selected="false">
                            Ingredients
                        </button>
                    </li>
                    <li role="presentation">
                        <button class="tab-btn inline-block p-4 border-b-2 rounded-t-lg hover:text-gray-300 hover:border-gray-300" 
                                id="instructions-tab" type="button"
                                data-tab="instructions"
                                aria-selected="false">
                            Instructions
                        </button>
                    </li>
                </ul>
            </div>

            <!-- Tab contents -->
            <div id="tab-content">
                <!-- Details tab -->
                <div class="tab-panel p-4 rounded-lg bg-gray-50 dark:bg-gray-800 text-white" 
                    id="Details" role="tabpanel" aria-labelledby="Details-tab" style="display: block;">
                    <div class='flex flex-col space-y-2'>
                        <h2 class="text-lg font-semibold">Name: <span class="font-normal">{{ recipe.name }}</span></h2>
                        <p>Author: {{ recipe.created_by }}</p>
                    </div>
                </div>

                <!-- Description tab -->
                <div class="tab-panel p-4 rounded-lg bg-gray-50 dark:bg-gray-800 text-white" 
                    id="description" role="tabpanel" aria-labelledby="description-tab" style="display: none;">
                    {{ recipe.description }}
                </div>

                <!-- Ingredients tab -->
                <div class="tab-panel p-4 rounded-lg bg-gray-50 dark:bg-gray-800 text-white" 
                    id="ingrediants" role="tabpanel" aria-labelledby="ingrediants-tab" style="display: none;">
                    {% if ing %}
                        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
                            <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                                    <tr>
                                        <th scope="col" class="px-6 py-3">Name</th>
                                        {% if request.user == recipe.created_by %}
                                            <th scope="col" class="px-6 py-3"><span class="sr-only">Edit</span></th>
                                            <th scope="col" class="px-6 py-3"><span class="sr-only">Delete</span></th>
                                        {% endif %}
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for i in ing %}
                                        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 border-gray-200 hover:bg-gray-50 dark:hover:bg-gray-600">
                                            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                                {{ i.name }}
                                            </th>
                                            {% if request.user == recipe.created_by %}
                                                <td class="px-6 py-4 text-right">
                                                    <a href="{% url "recipe:create_ingrediants" recipe.id %}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">ADD</a>
                                                </td>
                                                <td class="px-6 py-4 text-right">
                                                    <a href="{% url "recipe:update_ingrediants" recipe.id i.id  %}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                                                </td>
                                                <td class="px-6 py-4 text-right">
                                                    <a href="{% url 'recipe:delete_ingrediants' id_of_recipe=recipe.id id=i.id %}" class="font-medium text-blue-600 dark:text-red-500 hover:underline">Delete</a>
                                                </td>
                                            {% endif %}
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>

                        {% else %}

                            {% if request.user == recipe.created_by %}
                            <td class="px-6 py-4 text-right">
                                <a href="{% url "recipe:create_ingrediants" recipe.id %}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">ADD</a>
                            </td>
                            
                            {% endif %}
                    {% endif %}
                </div>


                <!-- Instructions tab -->
                <div class="tab-panel p-4 rounded-lg bg-gray-50 dark:bg-gray-800 text-white" 
                    id="instructions" role="tabpanel" aria-labelledby="instructions-tab" style="display: none;">
                    {% if ins %}
                        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
                            <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                                    <tr>
                                        <th scope="col" class="px-6 py-3">
                                            Step number
                                        </th>
                                        <th scope="col" class="px-6 py-3">
                                            Instructions
                                        </th>

                                        {% if request.user == recipe.created_by %}
                                        <th scope="col" class="px-6 py-3">
                                            <span class="sr-only">Edit</span>
                                        </th>
                                        <th scope="col" class="px-6 py-3">
                                            <span class="sr-only">Delete</span>
                                        </th>
                                        {% endif %}
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for i in ins %}
                                        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 border-gray-200 hover:bg-gray-50 dark:hover:bg-gray-600">
                                            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                                {{i.step_number}}
                                            </th>
                                            <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                                {{i.instruction_text}}
                                            </th>

                                            {% if request.user == recipe.created_by %}
                                            <td class="px-6 py-4 text-right">
                                                <a href="{% url "recipe:update_instruction" recipe.id i.id %}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                                            </td>
                                            <td class="px-6 py-4 text-right">
                                                <a href="{% url "recipe:delete_instructions" recipe.id i.id %}"class="font-medium text-blue-600 dark:text-red-500 hover:underline">Delete</a>
                                            </td>
                                            {% endif %}
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div> 

                        {% else %}
                            {% if request.user == recipe.created_by %}
                                <td class="px-6 py-4 text-right">
                                    <a href="{% url "recipe:create_instruction" recipe.id %}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">ADD</a>
                                </td>
                            {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Tab switching JS -->
<script>
document.addEventListener("DOMContentLoaded", function() {
    const tabs = document.querySelectorAll(".tab-btn");
    const tabPanels = document.querySelectorAll(".tab-panel");

    tabs.forEach(tab => {
        tab.addEventListener("click", function() {
            // Remove active styles
            tabs.forEach(t => t.classList.remove("border-blue-600", "text-blue-600"));
            tabs.forEach(t => t.setAttribute("aria-selected", "false"));

            // Activate clicked tab
            this.classList.add("border-blue-600", "text-blue-600");
            this.setAttribute("aria-selected", "true");

            // Hide all panels
            tabPanels.forEach(panel => panel.style.display = "none");

            // Show selected
            const tabName = this.getAttribute("data-tab");
            document.getElementById(tabName).style.display = "block";
        });
    });
});
</script>
{% endblock content %}

recipe/templates/recipe/view_recipes.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}

<div class = 'max-w-screen-xl mx-auto'>

    <div>
        <form method = 'get' action ="{% url 'recipe:view_recipes' %}">
            <div class="flex">
                <label for="search-dropdown" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Your Email</label>
                <button id="dropdown-button" data-dropdown-toggle="dropdown" class="shrink-0 z-10 inline-flex items-center py-2.5 px-4 text-sm font-medium text-center text-gray-900 bg-gray-100 border border-gray-300 rounded-s-lg hover:bg-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:ring-gray-700 dark:text-white dark:border-gray-600" type="button">All categories <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
        </svg></button>
                <div id="dropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow-sm w-44 dark:bg-gray-700">
                    <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdown-button">
                        {% if categories %}
                            {% for category in categories %}
                                <li>
                                    <a href="{% url 'recipe:view_recipes' %}?query={{query}}&category={{category.id}}" 
                                    type="button" 
                                    class="inline-flex w-full px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">
                                    {{category.name}}
                                    </a>
                                </li>
                                {% endfor %}
                            {% else %}
                            <li>
                                <p>Empty Category</p>
                            </li>
                        {% endif %}
                    </ul>
                </div>
                <div class="relative w-full">
                    <input type="search" name='query' value = '{{query}}' id="search-dropdown" class="block p-2.5 w-full z-20 text-sm text-gray-900 bg-gray-50 rounded-e-lg border-s-gray-50 border-s-2 border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-s-gray-700  dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:border-blue-500" placeholder="Search Mockups, Logos, Design Templates..." required />
                    <button type="submit" class="absolute top-0 end-0 p-2.5 text-sm font-medium h-full text-white bg-blue-700 rounded-e-lg border border-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                        <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                        </svg>
                        <span class="sr-only">Search</span>
                    </button>
                </div>
            </div>
        </form>


    </div>

    <div class= 'mt-3'>
        {% if recipes %}
        <div class='flex flex-wrap'>
            {% for recipe in recipes %}
                <div class="w-full max-w-sm m-4 bg-white border border-gray-200 rounded-lg shadow-sm dark:bg-gray-800 dark:border-gray-700">
                    <a href="{% url "recipe:view_recipe_detail" recipe.id %}">
                        <img class="w-full h-28 object-cover rounded-t-lg" src="{{recipe.image.url}}" alt="" />
                    </a>
                    <div class="p-5">
                        <a href="#">
                            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{recipe.name}}</h5>
                        </a>
                        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{recipe.description}}</p>
                        </a>
                    </div>
                </div>
            
            {% endfor %}
        </div>

        {% else %}
        <div class='flex justify-center'>
            <img src="{% static "images/empty.svg" %}" class='h-96' alt="">

        </div>
        
        {% endif %}
    </div>

</div>

{% endblock content %}

recipe/templates/recipe/view_user_recipes.html
{% extends "core/base.html" %}
{% load static %}

{% block content %}

<h1>my recipes</h1>

<h1><a href="{% url 'recipe:create_recipe' %}">add recipe</a></h1>

<div class='flex flex-wrap'>
            {% for recipe in recipes %}
                <div class="w-full max-w-sm m-4 bg-white border border-gray-200 rounded-lg shadow-sm dark:bg-gray-800 dark:border-gray-700">
                    <a href="{% url "recipe:view_recipe_detail" recipe.id %}">
                        <img class="w-full h-28 object-cover rounded-t-lg" src="{{recipe.image.url}}" alt="" />
                    </a>
                    <div class="p-5">
                        <a href="#">
                            <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">{{recipe.name}}</h5>
                        </a>
                        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">{{recipe.description}}</p>
                        </a>
                    </div>
                </div>
            
            {% endfor %}
        </div>

{% endblock content %}